<a href="https://colab.research.google.com/github/OsvaldoFloresC/OsvaldoFloresC/blob/main/Eliminaci%C3%B3n_Gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Eliminación gaussiana con sustitución hacia atrás.**
La eliminación gaussiana es un método matemático utilizado para resolver sistemas de ecuaciones lineales. Este método transforma una matriz aumentada (que incluye los coeficientes y los términos independientes de un sistema de ecuaciones) en una matriz triangular superior mediante una serie de operaciones de fila.

In [ ]:
import numpy as np

def eliminacion_gaussiana(A):
    n = A.shape[0]  # Número de filas de la matriz A

    print("Matriz Aumentada Inicial:")
    print(A)

    # Proceso de Eliminación Gaussiana
    for i in range(n):
        # Encontrar el mayor pivote absoluto en la columna actual
        max_row_index = np.argmax(abs(A[i:, i])) + i
        if A[max_row_index, i] == 0:
            raise ValueError("El sistema no tiene solución única (pivote nulo encontrado).")

        # Intercambiar la fila actual con la fila del mayor pivote
        if i != max_row_index:
            A[[i, max_row_index]] = A[[max_row_index, i]]

        # Eliminar los elementos debajo del pivote
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - factor * A[i, i:]

        # Imprimir la matriz después de la eliminación de cada columna
        print(f"\nMatriz después de la eliminación en la columna {i + 1}:")
        print(A)

    # Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (A[i, -1] - np.dot(A[i, i + 1:n], x[i + 1:n])) / A[i, i]

    # Imprimir la matriz después de la sustitución hacia atrás
    print("\nMatriz reducida:")
    print(A)

    return x

# Definición de la matriz aumentada
A = np.array([[  1, -1,  2, -1, -8],
              [  2, -2,  3, -3, -20],
              [  1,  1,  1,  0, -2],
              [  1, -1,  4,  3,  4]], dtype=float)

# Llamar a la función y obtener la solución
solucion = eliminacion_gaussiana(A)
print("\nSolución del sistema:")
for i in range(len(solucion)):
    print(f"x{i+1} = {solucion[i]:.1f}")


Matriz Aumentada Inicial:
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]

Matriz después de la eliminación en la columna 1:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    0.    0.5   0.5   2. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]]

Matriz después de la eliminación en la columna 2:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    0.5   0.5   2. ]
 [  0.    0.    2.5   4.5  14. ]]

Matriz después de la eliminación en la columna 3:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]
 [  0.    0.    0.   -0.4  -0.8]]

Matriz después de la eliminación en la columna 4:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]
 [  0.    0.    0.   -0.4  -0.8]]

Matriz reducida:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]
 [  0.  

La eliminación gaussiana es un método muy efectivo y se utiliza ampliamente en matemáticas, ingeniería y ciencias para resolver sistemas de ecuaciones lineales.