<a href="https://colab.research.google.com/github/OsvaldoFloresC/OsvaldoFloresC/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Factorización LU**
La factorización LU es un método utilizado en álgebra lineal para descomponer una matriz en el producto de una matriz triangular. Este método es muy útil para resolver sistemas de ecuaciones lineales, calcular determinantes y encontrar inversas de matrices.

$$A = LU $$
$L$ es una matriz triangular inferior de tamaño $n * n$ con unos en la diagonal principal.

$U$ es una matriz triangular superior de tamaño $n * n$

In [2]:
import numpy as np

def factorizacion_lu(A):
    n = A.shape[0]
    L = np.eye(n)  # Inicializamos L como una matriz identidad
    U = np.zeros((n, n))  # Inicializamos U como una matriz de ceros

    for i in range(n):
        # Paso 1: Seleccionar lii y uii
        U[i, i] = A[i, i] - sum(L[i, k] * U[k, i] for k in range(i))
        if U[i, i] == 0:
            print("Factorización imposible")
            return None, None

        # Paso 2: Calcular los elementos de la fila i de U y de la columna i de L
        for j in range(i + 1, n):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

    return L, U

def sustitucion_progresiva(L, b):
    n = L.shape[0]
    y = np.zeros_like(b, dtype=np.float64)  # Vector para almacenar las soluciones intermedias

    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])  # Sustitución hacia adelante

    return y

def sustitucion_regresiva(U, y):
    n = U.shape[0]
    x = np.zeros_like(y, dtype=np.float64)  # Vector para almacenar la solución final

    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]  # Sustitución hacia atrás

    return x

# Matriz de entrada
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

# Vector b
b = np.array([4, 1, -3, 4], dtype=float)

# Realizamos la factorización LU
L, U = factorizacion_lu(A)

if L is not None and U is not None:
    print("Matriz L:")
    print(L)
    print("\nMatriz U:")
    print(U)

    # Solucionamos el sistema LY = b
    y = sustitucion_progresiva(L, b)
    print("\nSolución del sistema LY = b (vector y):")
    print(y)

    # Solucionamos el sistema UX = Y
    x = sustitucion_regresiva(U, y)
    print("\nSolución del sistema UX = Y (vector x):")
    print(x)


Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Solución del sistema LY = b (vector y):
[  4.  -7.  13. -13.]

Solución del sistema UX = Y (vector x):
[-1.  2.  0.  1.]


La factorización LU no solo facilita la resolución de sistemas lineales complejos, sino que también es una herramienta fundamental para diversas aplicaciones en matemáticas y ciencias.