<a href="https://colab.research.google.com/github/OsvaldoFloresC/OsvaldoFloresC/blob/main/Pivoteo_parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Eliminación gaussiana con pivoteo parcial**
El pivoteo parcial es una mejora de la eliminación gaussiana que se utiliza para aumentar la estabilidad numérica y evitar errores debido a divisiones por números muy pequeños o cercanos a cero. En lugar de usar siempre el elemento de la diagonal principal como pivote, el pivoteo parcial selecciona el mayor valor absoluto en la columna actual y permuta la fila correspondiente con la fila del pivote.

El pivoteo parcial:
Selecciona el mayor valor absoluto en la columna actual como pivote, mejorando la estabilidad numérica con ello minimiza el riesgo de inestabilidad numérica.

In [ ]:
import numpy as np

def eliminacion_gaussiana_pivoteo_parcial(A):
    n = A.shape[0]  # Número de filas de la matriz A

    print("Matriz Aumentada Inicial:")
    print(A)

    # Proceso de Eliminación Gaussiana con Pivoteo Parcial
    for i in range(n):
        # Encontrar el mayor pivote absoluto en la columna actual
        max_row_index = np.argmax(abs(A[i:, i])) + i
        if A[max_row_index, i] == 0:
            raise ValueError("El sistema no tiene solución única (pivote nulo encontrado).")

        # Intercambiar la fila actual con la fila del mayor pivote
        if i != max_row_index:
            A[[i, max_row_index]] = A[[max_row_index, i]]

        # Eliminar los elementos debajo del pivote
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - factor * A[i, i:]

        # Imprimir la matriz después de la eliminación de cada columna
        print(f"\nMatriz después de la eliminación en la columna {i + 1}:")
        print(A)

    # Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (A[i, -1] - np.dot(A[i, i + 1:n], x[i + 1:n])) / A[i, i]

    # Imprimir la matriz después de la sustitución hacia atrás
    print("\nMatriz reducida:")
    print(A)

    return x

# Definición de la matriz aumentada
A = np.array([[0.003000, 59.14, 59.17],
              [5.291, -6.130, 46.78]], dtype=float)

# Llamar a la función y obtener la solución
solucion = eliminacion_gaussiana_pivoteo_parcial(A)
print("\nSolución del sistema:")
for i in range(len(solucion)):
    print(f"x{i+1} = {solucion[i]:.0f}")


Matriz Aumentada Inicial:
[[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]]

Matriz después de la eliminación en la columna 1:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Matriz después de la eliminación en la columna 2:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Matriz reducida:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Solución del sistema:
x1 = 10
x2 = 1


la eliminación gaussiana es un método fundamental y eficiente para resolver sistemas de ecuaciones lineales. Sin embargo, cuando se aplica directamente, puede sufrir problemas de estabilidad numérica, especialmente si los coeficientes de la matriz tienen magnitudes muy diferentes.

El pivoteo parcial es una técnica crucial para garantizar la precisión y estabilidad de la eliminación gaussiana en la resolución de sistemas de ecuaciones lineales, especialmente en aplicaciones científicas y de ingeniería.