<a href="https://colab.research.google.com/github/OsvaldoFloresC/OsvaldoFloresC/blob/main/Tutonumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Este es un breve tutorial sobre la libreria NUMPY

numpy (Numerical Python) es una biblioteca que permite manejar arrays y matrices multidimensionales de datos de manera eficiente. También proporciona una colección de funciones matemáticas para operaciones rápidas en estos arrays. \

\
Es importantante por su:  \
Eficiencia: numpy está implementado en C, por lo que es mucho más rápido que listas anidadas de Python para operaciones matemáticas.

Funcionalidad: Ofrece herramientas para integrar C/C++ y Fortran, y funciones matemáticas complejas como transformadas de Fourier, álgebra lineal, y estadísticas.

In [2]:
import numpy as np

mi_array = np.array([[[1,2,3],[4,6,7]], [[5,8,2],[4,0,9]]]) #Combinancion de arrays para formar una matriz

#imprime la matriz
print(mi_array)

#Este comando imprime el número de dimensiones del array
print(mi_array.ndim)

#Este comando selecciona y muestra el primer array en mi_array
print(mi_array[0])

#Este comando selecciona y muestra el primer array de la segunda fila.
print(mi_array[1,0])

#Este comando selecciona y muestra el elemento específico en la matriz/fila/columna indicadas.
print(mi_array[0,1,2])


[[[1 2 3]
  [4 6 7]]

 [[5 8 2]
  [4 0 9]]]
3
[[1 2 3]
 [4 6 7]]
[5 8 2]
7


Con la función reshape reorganiza los elementos del array en la nueva forma especificada.

Este es un ejemplo excelente de cómo numpy facilita la manipulación de matrices y arrays de manera eficiente y clara.

In [3]:
mi_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Imprimir la forma del array
print(np.shape(mi_array))  # Salida: (2, 4)

# Imprimir el array original
print(mi_array)

# Cambiar la forma del array a (4, 2)
mi_array = mi_array.reshape(4, 2)

# Imprimir el array con la nueva forma
print(mi_array)


(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Al trabajar con arrays de múltiples dimensiones en NumPy, necesitamos utilizar bucles anidados para acceder a cada elemento.

In [4]:
mi_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Imprimir todos los elementos del array con bucles anidados
#Primer bucle: Itera a través de cada sub-matriz en el array.
for matriz in mi_array:
  #Segundo bucle: Itera a través de cada fila en cada sub-matriz.
    for fila in matriz:
      #Tercer bucle: Itera a través de cada elemento en cada fila y lo imprime
        for elemento in fila:
            print(elemento)


1
2
3
4
5
6
7
8
9
10
11
12


arr1 y arr2 son matrices de 2x2.

La función np.concatenate((arr1, arr2), axis=1) concatena arr1 y arr2 horizontalmente a lo largo del eje 1.

In [5]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

# Concatenar los arrays a lo largo del eje 1 (horizontalmente)
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Dividir un array es útil para:

Paralelización: Mejorar la eficiencia distribuyendo el trabajo.

Análisis por partes: Facilitar el análisis de datos grandes.

Algoritmos específicos: Trabajar de manera efectiva con algunos algoritmos.

Entrenamiento de modelos: Evaluar el rendimiento en aprendizaje automático.

In [6]:
arr =  np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3) #El array se puede dividir

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


np.where te proporciona las posiciones (índices) en el array donde el valor es igual a 4. En este caso, los valores 4 se encuentran en las posiciones 3, 5 y 6 del array.

In [7]:
arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr == 4) #forma de buscar en un array

print(x)

(array([3, 5, 6]),)


np.sort ordena los elementos del array en orden ascendente. En este caso, los elementos se ordenan de menor a mayor: [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
arr = np.array([8,9,4,6,3,2,7,1,5])

print(np.sort(arr)) #ordena los elementos

[1 2 3 4 5 6 7 8 9]


Numeros Aleatorios \
En Numpy, los números aleatorios se generan utilizando funciones del módulo **numpy.random.** Este módulo proporciona herramientas para generar diferentes tipos de números aleatorios, lo cual es útil para simulaciones, análisis estadístico, aprendizaje automático y muchos otros fines científicos y de ingeniería.

Enteros aleatorios (random.randint): Genera números enteros aleatorios en un rango específico

In [9]:
from numpy import random

# Genera un número entero aleatorio entre 0 y 49
numero = random.randint(50)
print(numero)

# Genera un número de punto flotante aleatorio entre 0 y 1
numero = random.rand()

# Redondea el número a tres decimales y lo imprime
print(round(numero, 3))

# Suma 5 al número redondeado y lo imprime
print(round(numero, 3) + 5)

# Genera un array 3x3 de números de punto flotante aleatorios entre 0 y 1
array = np.random.random((3, 3))
print(array)

# Genera un número aleatorio siguiendo una distribución normal
numero = np.random.randn()
print(numero)


36
0.788
5.788
[[0.38815346 0.51841316 0.92648653]
 [0.94799488 0.28571202 0.11483065]
 [0.5022453  0.02619509 0.01726183]]
-0.8221318191060264


random.choice de Numpy se utiliza para seleccionar un elemento al azar de una lista o array.

In [10]:
lista_nombres =["Bob","Dexter","Scooby","Vaca","Edd","Ash","Ben","Ioga","Ferb"]

# selecciona a un ganador
ganador = random.choice(lista_nombres)
print("El ganador del sorteo es: "+ ganador)

# selecciona al menos a 3 ganadores
ganador = random.choice(lista_nombres, size=(3))
print(ganador)

# crea una matriz de 3 filas y 5 columnas
ganador = random.choice(lista_nombres, size=(3,5))
print(ganador)


El ganador del sorteo es: Bob
['Bob' 'Vaca' 'Ben']
[['Dexter' 'Vaca' 'Edd' 'Ash' 'Bob']
 ['Vaca' 'Dexter' 'Ash' 'Dexter' 'Scooby']
 ['Ferb' 'Bob' 'Scooby' 'Bob' 'Ferb']]


En lo general, Numpy es una biblioteca esencial para trabajar con datos en Python debido a su eficiencia y funcionalidades como:

Operaciones matemáticas y estadísticas: Numpy ofrece un amplio conjunto de funciones para realizar cálculos matemáticos y estadísticos, como sumas, productos, medias, desviaciones estándar y mucho más.

In [11]:
arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))  # Media
print(np.std(arr))   # Desviación estándar


3.0
1.4142135623730951


Manipulación de datos: Numpy permite realizar operaciones avanzadas de manipulación de datos, como transponer matrices, invertir matrices y realizar operaciones de álgebra lineal.

In [12]:
matrix = np.array([[1, 2], [3, 4]])

print(matrix) # Matriz
print(np.transpose(matrix))  # Transponer matriz
print(np.linalg.inv(matrix))  # Invertir matriz


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Transformaciones de datos: Con Numpy, puedes realizar transformaciones como la normalización y escalado de datos, lo cual es crucial en el preprocesamiento de datos para el aprendizaje automático.

In [13]:
arr = np.array([1, 2, 3, 4, 5])

normalized_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized_arr)  # Normalizar datos


[0.   0.25 0.5  0.75 1.  ]


Creación de datos estructurados: Puedes crear arrays estructurados con tipos de datos específicos, lo cual es útil para manejar datos heterogéneos.

In [14]:
data = np.array([(1, 'Alice', 25), (2, 'Bob', 30)], dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4')])

print(data['name'])  # Obtener nombres


['Alice' 'Bob']


Integración con otras bibliotecas: Numpy se integra perfectamente con otras bibliotecas científicas y de datos en Python, como Pandas, SciPy y Matplotlib, facilitando el análisis y la visualización de datos. \
La importancia que tiene numpy es fundamental para trabajos científicos, análisis de datos y desarrollo de algoritmos en Python.